### ISSUE TITLE
Fear into db casues opponent to freecast during fear

### ISSUE THREAD

**Issue by pqbugreporter** [Project-Deus/Deus-Classless-Issues#100]
**Describe the bug**
when you fear and then db a feared target together, when db drops off you are still feared but you can free cast or attack with anything during the remaining fear, for example i can arcane barrage my target whilst feared

**To Reproduce**
1. start a duel
2. fear the opponent
3. dragons breath the opponent right after
4. db drops off and fear is still up
5. opponent can now free cast on you

**Expected behavior**
db drops off, opponent can free cast
**Screenshots**
![image](https://user-images.githubusercontent.com/96506777/147397335-8b5fd92e-06f2-4f53-abe4-3148dc999e2d.png)

**Additional context**
only seems to work with these 2 cc in this order, no other cc and order can replicate.

**Comment by Blandmarrow** [comment]
Confirmed report.
