### ISSUE TITLE
Revealing strike still putting interrupts on GCD

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#105]
**Describe the bug**
Revealing strike puts interrupts, most defensives like deterrence, ice block, vanish and other abilities not on GCD on cooldown.

**To Reproduce**
1. Press Revealing Strike
2. Try casting kick, pummel, deterrence, ice block, vanish, shadow step/any ability not normally on the GCD at the same time you press revealing strike
3. Ability will fail to cast because it is on a 1 second GCD

**Expected behavior**
Revealing strike not to put abilities such as interrupts and defensives on GCD

**Comment by Blandmarrow** [comment]
Confirmed report.

CLARIFICATION:
Revealing Strike puts GCD on abilities that should NOT have GCD, like counterspell.
It also does not trigger GCD on abilities that SHOULD have GCD, like stormstrike.

Basically it is doing the inverse of what it should be doing.

**Comment by UltraNix** [comment]
Clientside bug.

**Comment by UltraNix** [comment]
Fixed.
