### ISSUE TITLE
Hoj into DB overlap = thunderstorm able to be used

### ISSUE THREAD

**Issue by Above01** [Project-Deus/Deus-Classless-Issues#111]
**Describe the bug**
Hoj into Dragons breath cc overlap, hoj runs out whilst db is still active and thunderstorm is able to be cast

**To Reproduce**
1. Hoj and db target
2. Wait for hoj to run out
3. Target can thunderstorm

**Expected behavior**
^

**Screenshots**

**Comment by Blandmarrow** [comment]
Should be related to https://github.com/Project-Deus/Deus-Classless-Issues/issues/100

Most likely anything is castable if you use DB on someone and it runs out, while the previous CC is still in effect.
