### ISSUE TITLE
Spell Reflect does not work on Dots

### ISSUE THREAD

**Issue by Blandmarrow** [Project-Deus/Deus-Classless-Issues#114]
**Describe the bug**
Spell reflect seems to only work on direct spells, not any kind of Dot.

**To Reproduce**
1. Have target cast spell reflect
2. Cast a dot
3. Will not reflect the dot

**Expected behavior**
The dot should be reflected.

**Screenshots**

**Additional context**
ID: 23920

**Comment by UltraNix** [comment]
Works okay.
