### ISSUE TITLE
Premeditation proccing Overpower

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#117]
**Describe the bug**
Premeditation (SpellID: 14183) giving a free proc of overpower, even without Taste for Blood talented.

**To Reproduce**
1. Learn Premeditation, Stealth or Shadow Dance
2. Use Premeditation in Stealth or Shadow Dance
3. Get a free proc on Overpower

**Comment by Blandmarrow** [comment]
Confirmed report.

**Comment by Drakeare** [comment]
Seems like Overpower procs from ALL things related to combo points. All combo generators from Rogue AND Druid proc overpower. Also talents that generate combo points such as Honor Among Thieves proc Overpower.

**Comment by UltraNix** [comment]
Connected with #22

**Comment by UltraNix** [comment]
Fixed.
