### ISSUE TITLE
Can't cast Hand of Sacrifice 

### ISSUE THREAD

**Issue by qochwip** [Project-Deus/Deus-Classless-Issues#118]
**Describe the bug**
When trying to cast Hand of Sacrifice you get an error message saying the target is too low level.

**To Reproduce**
1. Pick Hand of Sacrifice spell
2. Try to cast it on a party member

**Expected behavior**
For Sac to work on party members regardless of the level.

**Screenshots**
![image](https://user-images.githubusercontent.com/86960425/147576172-0f5d00e7-8926-4956-9dea-5026fbb81c3c.png)

**Additional context**
None.

**Comment by Blandmarrow** [comment]
Confirmed report.
