### ISSUE TITLE
Sinister Strike procs Overpower

### ISSUE THREAD

**Issue by Blandmarrow** [Project-Deus/Deus-Classless-Issues#120]
**Describe the bug**
Sinister Strike procs Overpower.

**To Reproduce**
1. Pick Overpower & Sinister Strike
2. Cast Sinister Strike
3. Overpower procs

**Expected behavior**
Overpower should not be procced by sinister strike

**Screenshots**

**Additional context**
IDs:
Sinister Strike: 1752
Overpower: 7384

**Comment by Drakeare** [comment]
Seems like Overpower also procs from Garrote. SpellID: 703

**Comment by UltraNix** [comment]
Duplicate of #117
