### ISSUE TITLE
Arcane missiles bug

### ISSUE THREAD

**Issue by Above01** [Project-Deus/Deus-Classless-Issues#121]
**Describe the bug**
Every spell currently procs arcane missiles 100% however arcane missiles cannot be used

**To Reproduce**
^

**Expected behavior**
A proc chance for arcane missiles 

**Screenshots**
https://gyazo.com/87e5b10b3bb0564090de896c34bb76c9
https://gyazo.com/34d30d54b732534927784ae1c837a9f1

**Additional context**
Just seems like arcane missiles isn't a working ability currently and that every spell gives the proc for it 100% of the time. e.g Dragons breath on the pack of 4 dummies gives 4 procs

**Comment by Drakeare** [comment]
Also proccing on melee abilities like Mortal Strike

**Comment by Blandmarrow** [comment]
Confirmed report.
