### ISSUE TITLE
Incite, heroic strike talent abnormal behavior

### ISSUE THREAD

**Issue by starksson** [Project-Deus/Deus-Classless-Issues#123]
Incite talent procs abnormal behaviour, from procs of each other to no procs at all ~3 times procs of each other and then 3 heroic strikes no proc at all. 

1. Pick Heroic Strike and Incite talent
2. Cast Heroic Strike
3. Weird behaviour/procs

Incite should make your next Heroic Strike a guaranteed crit but Incite Should not proc from another Incite Heroic Strike

**Comment by Blandmarrow** [comment]
Unable to replicate issue, worked fine during test.
