### ISSUE TITLE
Divine Shield

### ISSUE THREAD

**Issue by Kev500** [Project-Deus/Deus-Classless-Issues#125]
**Describe the bug**
Divine Shield is Unuseable during the debuff Hypothermia that you get from using Ice Block.

**To Reproduce**
1. Get Ice Block and Divine Shield
2. Use Ice Block and try to use Divine Shield afterwards
3. See error

**Expected behavior**
Divine Shield should only not be useable during forbearance debuff.

**Comment by starksson** [comment]
I've also had problems trying to use it when I duel a lot and I didn't have ice block at the time. Pretty sure I wasn't CCed or silenced either.

**Comment by Blandmarrow** [comment]
Confirmed report about Hypothermia blocking the use of Divine Shield.

**Comment by UltraNix** [comment]
Works okay.
