### ISSUE TITLE
FoF not proccing from blizzard

### ISSUE THREAD

**Issue by pqbugreporter** [Project-Deus/Deus-Classless-Issues#126]
**Describe the bug**
talent [ice shards] gives blizz a chill effect, chill effect = [Fingers of Frost] proc. 
blizzard never gives an FoF proc however
**To Reproduce**
1. learn blizz, Fof and ice shards
2. cast blizz
3. see 0 procs

**Expected behavior**
gives fof procs on a 20% chance
**Screenshots**
![image](https://user-images.githubusercontent.com/96506777/147707188-922c6ea6-9e8d-418c-b7b0-14b8209d51d2.png)
![image](https://user-images.githubusercontent.com/96506777/147707193-d3109e43-4731-4b11-b8a0-e25b5e2a7913.png)

**Additional context**

**Comment by Blandmarrow** [comment]
Confirmed report.
