### ISSUE TITLE
Honor Among Thieves not building combo points on new current target

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#127]
Honor Among Thieves will continue to build combo points on the previous target if you have at least one combo point on that previous target, even if that enemy is not your current target and are attacking/targeting something else.

**To Reproduce**
1. Have at least one combo point on a target
2. Swap targets and try getting a critical strike and proc Honor Among Thieves on the new target
3. Check previous target to see new combo points

**Expected behavior**
Honor Among Thieves to build combo points on your CURRENT target.

ID: 51700

**Comment by Blandmarrow** [comment]
Confirmed report.

However this feels like it might be a intended thing as to not remove existing combo points if you by mistake were to proc it on another target.
