### ISSUE TITLE
Frost shock and Exorcism share cooldown

### ISSUE THREAD

**Issue by Luiswastaken** [Project-Deus/Deus-Classless-Issues#128]
**Describe the bug**
Using frost shock will put exorcism on cooldown, oddly only works that way. Using exorcism won't put frost shock on cooldown.

**To Reproduce**
Use frost shock before Exorcism and it will be put on cooldown.

**Expected behavior**
They shouldnt share cd

**Comment by Blandmarrow** [comment]
Issue added into https://github.com/Project-Deus/Deus-Classless-Issues/issues/75
