### ISSUE TITLE
Talent bug

### ISSUE THREAD

**Issue by flameskin2011** [Project-Deus/Deus-Classless-Issues#13]
Some talents i cant pick, i have enough points

**Comment by Blandmarrow** [comment]
Please be more specific, this only affects certain talents.

**Comment by Blandmarrow** [comment]
Report is correct, but is not specific.

One related incident to this is: https://github.com/Project-Deus/Deus-Classless-Issues/issues/1

**Comment by Blandmarrow** [comment]
CLARIFICATION:
When you learn these abilities, you lose the AE and do not learn the ability.
This is only fixed when you reset the build.
