### ISSUE TITLE
Cat form - Double hit

### ISSUE THREAD

**Issue by Blandmarrow** [Project-Deus/Deus-Classless-Issues#134]
**Describe the bug**
When the player dual wields, the auto hits in cat double hit, meaning you hit twice per paw, so 4 times per second instead of 2.

**To Reproduce**
1. Duel Wield
2. Pick cat and go into cat form
3. Auto hit target

**Expected behavior**
You should not double hit while dual wielding in cat form.

**Comment by Blandmarrow** [comment]
UPDATE: 
This is true for bear form as well.

**Comment by Blandmarrow** [comment]
UPDATE:
This is true for mookin form as well.

**Comment by Blandmarrow** [comment]
UPDATE: 
This is true for Tree of Life as well.

**Comment by UltraNix** [comment]
Works okay.
