### ISSUE TITLE
Make Gouge stop procing weapon procs

### ISSUE THREAD

**Issue by WarlordXecc** [Project-Deus/Deus-Classless-Issues#136]
Make Gouge stop procing weapon procs. For example if you have Windfury Weapon, Gouge wont CC cuz it will break instantly from windfury proc and other effects like it.

**Comment by UltraNix** [comment]
I don't understand that. Windfury Weapon procs on melee attack, so if you don't want it to proc, just stop attacking.

**Comment by WarlordXecc** [comment]
> I don't understand that. Windfury Weapon procs on melee attack, so if you don't want it to proc, just stop attacking.

No, the issue is that Gouge itself procs Windfury Weapon. Gouge already stops you from auto attacking your target. But the spell Gouge can proc Windfury meaning that Gouge instantly breaks.
Windfury Weapon and other Shaman Enchantments procs from Special Attacks also, Sinister Strike for example can proc it just like Gouge.
