### ISSUE TITLE
Hunter abilities costs Focus

### ISSUE THREAD

**Issue by UltraNix** [Project-Deus/Deus-Classless-Issues#137]
**Describe the bug**
Hunter abilities still cost Focus instead of Energy resource. The tooltips are good, but dbc data is not updated.

**To Reproduce**
1. Pick up Chimera Shot or Serpent Sting
2. Try to cast it.

**Expected behavior**
Updates DBC values for all hunter updated spells with correct power type.

**Screenshots**

**Additional context**

**Comment by kazuke353** [comment]
You don't have the modified DBCs in the core
