### ISSUE TITLE
Juggernaut and warbringer

### ISSUE THREAD

**Issue by flameskin2011** [Project-Deus/Deus-Classless-Issues#14]
cant pick any of those talents

**Comment by flameskin2011** [comment]
Unbreakable Will seems bugged aswell

**Comment by Blandmarrow** [comment]
Juggernaut and Unbreakable Will works.

Warbringer does not.

Related to https://github.com/Project-Deus/Deus-Classless-Issues/issues/1

**Comment by UltraNix** [comment]
Both works.
