### ISSUE TITLE
Talent AE price is red even if you have enough AE

### ISSUE THREAD

**Issue by Dawiss2** [Project-Deus/Deus-Classless-Issues#17]
![image](https://user-images.githubusercontent.com/25409605/146699165-d942d70d-29f5-4361-99a3-492557bb0d7e.png)

**Comment by Dawiss2** [comment]
![image](https://user-images.githubusercontent.com/25409605/146699219-6c4d5000-245a-4492-8a54-34e445482023.png)
just noticed now, happens with spells too not only talents

**Comment by Blandmarrow** [comment]
Tried this, report is not true.

Most likely related to visual bug for available AE and TE, so while it says 8 AE available, the user most likely does not have that much to spend.
