### ISSUE TITLE
your own buff's stay after resetting build,

### ISSUE THREAD

**Issue by frostboltx** [Project-Deus/Deus-Classless-Issues#18]
title says all

**Comment by Blandmarrow** [comment]
Confirmed report.

Talent passives such as Elemental oath wont stay.
However, something like Power Word: Fortitude or Blessing of Kings will keep you buffed even after you unlearn it.

**Comment by Blandmarrow** [comment]
This is true even if you relogg.

**Comment by Blandmarrow** [comment]
UPDATE:
Applies to weapon enchants as well.

**Comment by UltraNix** [comment]
Works okay.
