### ISSUE TITLE
Water Shield Bugged - Castable on other characters.

### ISSUE THREAD

**Issue by kylods** [Project-Deus/Deus-Classless-Issues#32]
Water Shield (Spell ID 52127) is castable on other players/npcs with a short cast distance.
![Screenshot_2021-12-19_23-57-06](https://user-images.githubusercontent.com/29592541/146718810-69e4ecdb-cc18-4f3d-b42e-9b1fbfb73fe8.png)

**Comment by Blandmarrow** [comment]
Intended function, was posted in #changelog on discord.
