### ISSUE TITLE
Arcane Tactics UI Bug

### ISSUE THREAD

**Issue by kylods** [Project-Deus/Deus-Classless-Issues#34]
Arcane Tactics can be successfully learned and consumes AE, but afterwards the UI doesn't register that it is a learned talent. Issue persists after relogging.

Screenshot of the bugged talent UI.
![Screenshot_2021-12-20_00-44-50](https://user-images.githubusercontent.com/29592541/146723521-94017ff4-9abe-4514-a02f-8adfff7618c7.png)

Screenshot of the buff in use.
![Screenshot_2021-12-20_00-44-37](https://user-images.githubusercontent.com/29592541/146723524-62ce561e-f6b5-4cab-a355-3c5368c244f4.png)

**Comment by kylods** [comment]
Totemic Wrath (Spell ID 77747) is also affected by this same bug.

**Comment by Blandmarrow** [comment]
Confirmed report.

Same issue as: https://github.com/Project-Deus/Deus-Classless-Issues/issues/28
