### ISSUE TITLE
Brain Freeze/Fingers of Frost Bugged Interaction

### ISSUE THREAD

**Issue by kylods** [Project-Deus/Deus-Classless-Issues#35]
When Frostfire Bolt(Spell ID 44614) is cast via a Brain Freeze(Spell ID 44549) proc, it also consumes a stack of Fingers of Frost(Spell ID 83074). Frostfire Bolt does not consume Fingers of Frost stacks while Brain Freeze is not active.

**Comment by Blandmarrow** [comment]
Intended function.
