### ISSUE TITLE
Seal of justice

### ISSUE THREAD

**Issue by heyxd123** [Project-Deus/Deus-Classless-Issues#52]
![Seal of justice](https://user-images.githubusercontent.com/96449680/146842515-d5cae4ae-ef94-4fe0-b0be-b5f4ff80ead1.PNG)

![Seal of justice Jetski](https://user-images.githubusercontent.com/96449680/146842823-fe00349e-11ab-43d0-9feb-3733330f054e.PNG)

Seal of justice is overtuned, for a passive damage ability. It should never be nr.1 or nr.2 damage.
2 screenshots showing it. First is my damage and the other one is jetski's SoJ,

**Comment by Blandmarrow** [comment]
Unable to replicate issue, most likely fixed.
