### ISSUE TITLE
Rampage bug

### ISSUE THREAD

**Issue by hardin017** [Project-Deus/Deus-Classless-Issues#54]
**Describe the bug**
Can learn but it takes away the AE and doesnt appear as learned, won't let you unlearn it either.
Edit: still functions even if it doesnt appear learned

**To Reproduce**
1. Go to 'Fury Talents'
2. Click on 'Rampage'
3. Learn Rampage
4. Try to unlearn it, finding your AE gone.

**Expected behavior**
Rampage suppose to learn and appear learned and be usable.

**Screenshots**
xd

**Additional context**
xd

**Comment by Blandmarrow** [comment]
Confirmed report.

Same as issue: https://github.com/Project-Deus/Deus-Classless-Issues/issues/28
