### ISSUE TITLE
Communion doesn't grant ability, still consumes AE.

### ISSUE THREAD

**Issue by kylods** [Project-Deus/Deus-Classless-Issues#55]
**Describe the bug**
Communion (Spell ID 31876) does not grant the talent when learned, still consumes AE. AE spent does not reappear when relogging.

**To Reproduce**
1. Go to Classless Spellbook
2. Click on Paladin > Communion Talent, click Learn
3. Talent is de-selected, AE is consumed.
4. Attempting to use a paladin aura does not grant the talent buff.

**Expected behavior**
Paladin auras are expected to provide the Communion buff to self and all party members. Alternatively, AE should not be consumed if the talent is temporarily deactivated.

**Additional context**
Similar to #34, though in this case it doesn't seem the ability is actually granted.

**Comment by Blandmarrow** [comment]
Issue is resolved, working fine atm.
