### ISSUE TITLE
Hunting party eats points permanently and does not work

### ISSUE THREAD

**Issue by Luiswastaken** [Project-Deus/Deus-Classless-Issues#60]
Hunting party 4 AE survival talent is pickable but doesnt work, ends up showing as unpicked but removes points

**To Reproduce**
1. Learn Hunting Party
2. Watch as you lose the AE
3. Cry in despair as you have to remake entire build
4. Hope that the gamer devs will fix soontm pogpog

Made a character to test, and i had 143 agi before and after picking talent.

**Expected behavior**
Should work. 

**Screenshots**
What my hunting party looks like after relogging. still ended up eating my 4 AE investement
![image](https://user-images.githubusercontent.com/96391269/146974860-2fa45a2d-d448-479f-aef1-db170da08611.png)

Talent only breaks after clicking learn
![image](https://user-images.githubusercontent.com/96391269/146975149-d72068d0-f670-48c2-b8ff-ba5a555fa3d4.png)

**Comment by Blandmarrow** [comment]
Confirmed report.

Issue related to: https://github.com/Project-Deus/Deus-Classless-Issues/issues/1

**Comment by Blandmarrow** [comment]
Parent report: https://github.com/Project-Deus/Deus-Classless-Issues/issues/13
