### ISSUE TITLE
Infinite TE bug

### ISSUE THREAD

**Issue by Luiswastaken** [Project-Deus/Deus-Classless-Issues#61]
**Describe the bug**
Somehow able to learn and unlrearn talents for infinite talent essence

**To Reproduce**
Not 100% sure how this ended up happening, just noticed that i could learn and unlearn some talents to gain Talent essence.
First i would learn a talent and the game would both give me the talent and refund my essence. It was then possible to unlearn the talent and gain the essence again. Effectively being able to get all the talents in the game.

Upon a relog it seems all the talents exceeding the cap become unlearned. But im then able to just spam more TE after.

![image](https://user-images.githubusercontent.com/96391269/147008201-db2b5cb3-095f-4a01-9302-f5b6db7f4ecd.png)
This is what i got after relogging.

![image](https://user-images.githubusercontent.com/96391269/147008503-c2e1ace1-a603-45f1-ac10-c0567a9340e7.png)
Here i have an impossible ammount of TE even with talents used.

**Additional context**
Seems to only work on some talents, especially the 3 point ones.

EDIT: seems like there are just a couple broken talents that refund both when you learn and when you unlearn.
So far ive noticed:
 "Sheath of Light" + "Touched by the Light" in the paladin tree.
 "Unbreakable Will" in the disc priest tree.
 "Sentinel" in the prot warrior tree.

**Comment by Blandmarrow** [comment]
Confirmed report.

CORRECTIONS:
This affects all passive talents that were introduced from when you choose the a spec in 4.3.4.
This does not seem to affect the AE abilities like Shamansim (ID 62099), only talents.
Some examples of this is:
Sentinel: ID 29144
Mental Quickness: ID 121836
Unbreakable Will: 121829
Unyielding Faith: ID: 121832

**Comment by Blandmarrow** [comment]
UPDATE:
Relogging fixes the issue, however still abuseable.

**Comment by Blandmarrow** [comment]
Issue is resolved.
