### ISSUE TITLE
Revealing strike shares GCD with wrong abilities

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#62]
Revealing strike shares global cooldown with abilities that such as shadow step, deterrence, kick, cold blood, etc. Abilities normally not on the GCD for most damaging abilities

**Comment by Luiswastaken** [comment]
Also been looking at this, and it isnt shared. Using Kick doesnt put Revealing Strike on cd, but using Revealing Strike does put all the other spells on gcd,

**Comment by Blandmarrow** [comment]
Unable to replicate issue, seems to be working fine.
