### ISSUE TITLE
Dots not hitting training dummies at all.

### ISSUE THREAD

**Issue by Ishnualah69** [Project-Deus/Deus-Classless-Issues#64]
Spells like, Unstable affliction, Shadow word:pain, Devouring plague is not hitting the training dummy at all, there is no miss, resist, nothing in combat log, spell just dissapears in to the void.

**Comment by Ishnualah69** [comment]
Correction, when i dealt damage with any other spell first i could start dotting them, but if no damage was dealt my dots would dissapear

**Comment by Blandmarrow** [comment]
Confirmed report.

You cannot cast dots on dummies unless you're already in combat with them.

**Comment by Blandmarrow** [comment]
UPDATE:

This applies to things like channeled abilities as well, like Drain Life.
