### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by Kev500** [Project-Deus/Deus-Classless-Issues#66]
**Describe the bug**
Consecration does not seem to do any dmg whatsoever it does not interact with anything.

**To Reproduce**
1. Go to 'Anything you can hit'
2. Click on 'Consecration'
3. Watch nothing as nothing happen

**Expected behavior**
Consecration doing damage

**Comment by Blandmarrow** [comment]
Confirmed report.

Consecrate does not hit any target standing in it.
