### ISSUE TITLE
spell reflect killing a player

### ISSUE THREAD

**Issue by pqbugreporter** [Project-Deus/Deus-Classless-Issues#67]
**Describe the bug**
using spell reflect to reflect a hit that would take the caster below 1hp kills the player
**To Reproduce**
get a low hp player
cast reflect
have them hit you with smth big
you die

**Expected behavior**
player dies in mall
**Screenshots**

**Additional context**
its rough since you need a gm respawn or another player on your facc still

**Comment by Blandmarrow** [comment]
Unable to replicate bug, seems to be working fine.
