### ISSUE TITLE
Holy Shock Mana Cost

### ISSUE THREAD

**Issue by Oondiv** [Project-Deus/Deus-Classless-Issues#68]
**Describe the bug**
The tooltip for Holy Shock is displaying an incorrect mana cost, or the spell itself is using an incorrect amount of mana.

**To Reproduce**
Simply just pick up Holy Shock, look at the tooltip, and cast it.

**Expected behavior**
The tooltip and the amount of mana it uses should be identical.

**Screenshots**
n/a

**Additional context**
I'm not sure which one is incorrect. Tooltip says 80 Mana, casting Holy Shock consumes ~250 Mana (it's hard to say for sure with how rapidly mana regenerates)

**Comment by Blandmarrow** [comment]
Confirmed report.

Holy Shock displays the wrong mana cost.

**Comment by UltraNix** [comment]
Looks okay.
