### ISSUE TITLE
Metamorphosis and Tree of Life visual bug

### ISSUE THREAD

**Issue by qochwip** [Project-Deus/Deus-Classless-Issues#69]
**Describe the bug**
If you go into Metamorphosis or Tree of Life and cast Berserker Stance you get permanent form visual.

**To Reproduce**
1. Cast Metamorphosis or Tree of Life
2. Use Berserker Stance
3. Profit?

**Expected behavior**
For Meta visual do disappear after the duration.

**Screenshots**
![image](https://user-images.githubusercontent.com/86960425/147147153-0bd471ab-b5d8-4fb6-af86-c45d1c4ca693.png)

**Additional context**
In the Screenshot you see Efo has no Meta or Tree of Life active, but the visual stays.

**Comment by UltraNix** [comment]
Looks okay.
