### ISSUE TITLE
Borrowed Time talent gives the wrong amount of haste

### ISSUE THREAD

**Issue by qochwip** [Project-Deus/Deus-Classless-Issues#73]
**Describe the bug**
One point on the priest Borrowed Time talent gives 7% haste, two points give 14% although the talent says 5%/10%.

**To Reproduce**
1. Put one or two points on the talent
2. Cast Power Word: Shield
3. Check your haste rating

**Expected behavior**
By casting Power Word: Shield you should get 5%/10% haste.

**Screenshots**
![image](https://user-images.githubusercontent.com/86960425/147168970-0353be71-f568-46f6-a0ae-fc702d441927.png)

Haste without PWS:
![image](https://user-images.githubusercontent.com/86960425/147169003-83befd51-4c39-49b7-b15d-ac70a9244b82.png)

Haste with one point in Borrowed Time + PWS:
![image](https://user-images.githubusercontent.com/86960425/147169050-4e89f00e-02a4-43bd-8222-19d4257922a9.png)

Haste with two points in Borrowed Time + PWS:
![image](https://user-images.githubusercontent.com/86960425/147169422-cadd7497-b9d4-4749-a4b9-856b9157dba6.png)

**Additional context**
Maybe the tooltip is wrong and you do get 7%/14% Haste.

**Comment by Blandmarrow** [comment]
Confirmed report.

Either tooltip is wrong or it gives more than it should.
