### ISSUE TITLE
Flame shock + Fire blast share cd

### ISSUE THREAD

**Issue by Above01** [Project-Deus/Deus-Classless-Issues#75]
**Describe the bug**
Flame shock and fire blast share the same cooldown

**To Reproduce**
Use one of the abilities

**Expected behavior**
Don't share cd

**Screenshots**
https://gyazo.com/0969a91a79d3b426e9aea354cf2e1b56

**Additional context**
Nope

**Comment by Blandmarrow** [comment]
Confirmed report.

Fire Blast and all shocks share CD.

**Comment by Blandmarrow** [comment]
UPDATE:
Mind Blast also shares CD with shocks.

**Comment by Blandmarrow** [comment]
UPDATE: 
Shocks and Fire blast also triggers CD on Exorcism.
