### ISSUE TITLE
Damage proc items such as Alcor's proccing talents

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#76]
Spell damage proc items such as Alcor's, Emerald dragonfang, Deathbringer etc. Can proc spell damage % talents such as Impact (fire mage), Arcane concentration (arcane mage), etc. This effect does not seem to work for talents that state non-crit damage like elemental focus (elemental shaman), etc.

**Comment by Blandmarrow** [comment]
Confirmed report.

Weapon spell procs (unclear about non spell ones) can proc above mentioned talent passives.

**Comment by UltraNix** [comment]
`Impact` description: "Gives your **damaging** spells [...]"
`Arcane Concentration` description: "[...] Clearcasting state after **any damage** spell hits a target"
I see no bug here.
