### ISSUE TITLE
Chaos bolt not going through shield

### ISSUE THREAD

**Issue by Above01** [Project-Deus/Deus-Classless-Issues#77]
**Describe the bug**
Chaos bolt supposed to 'pierce through absorptions' but doesn't

**To Reproduce**
Chaos bolt a shielded player

**Expected behavior**
Chaos bolt to go through shields

**Screenshots**

**Additional context**
Chaos bolt should be scary.

**Comment by Blandmarrow** [comment]
Confirmed report.

Chaos bolt currently does not go through absorbs.
