### ISSUE TITLE
Haunt issues, Shadow Embrace not wrorking.

### ISSUE THREAD

**Issue by Useless2491** [Project-Deus/Deus-Classless-Issues#79]
**Describe the bug**
The bug is that Haunt does not increase the shadow dots for priest (warlock doesn't seem to be working either). Shadow embrace does not increase periodic shadow damage.
**To Reproduce**
1. Go to '...' use haunt
2. Click on '....' priest dots c;
3. Scroll down to '....' recount/ watch the damage

**Expected behavior**
I expected my damage to be increased, but evidently it was not.
**Screenshots**

**Additional context**

**Comment by Blandmarrow** [comment]
Confirmed report.

However it is not a bug, it is a class masking feature that has not yet been implemented.

**Comment by Blandmarrow** [comment]
UPDATE: 
Warlock dots works fine, this only affects shadow priest dots.
