### ISSUE TITLE
Water Shield - Castable on infinite amount of friendly targets

### ISSUE THREAD

**Issue by Blandmarrow** [Project-Deus/Deus-Classless-Issues#80]
**Describe the bug**
You're able to cast Water shield and maintain it on infinite amount of friendly targets while having it on yourself as well.

**To Reproduce**
1. Cast Water Shield on Friendly targets.

**Expected behavior**
Water Shield should not be castable on more than 1 target.
Unclear if it should be on caster and 1 friendly target or only 1 target period.

**Screenshots**

**Additional context**

**Comment by UltraNix** [comment]
Tooltip is changed and says nothing about this restriction.
