### ISSUE TITLE
Improved serpent sting's instant proc effect being effected by Toxicology

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#82]
Improved serpent sting's effect of doing 30% damage of serpent's sting periodic effect is benefiting from Toxicology talent, which is giving at a 100% critical damage bonus

**Comment by Blandmarrow** [comment]
Expected behavior, however a bit strong perhaps.
Can crit with serpent sting up to 1k easily.

**Comment by UltraNix** [comment]
I see no bug here.
