### ISSUE TITLE
Using heal abilities in moonkin form

### ISSUE THREAD

**Issue by Ishnualah69** [Project-Deus/Deus-Classless-Issues#87]
You can use Holy shock, Circle of healing, Light of dawn in boomkin form.

**Comment by Blandmarrow** [comment]
Confirmed and correction to report:

You can currently cast spells that require casting of any other class other than druid inside moonkin form.
Note that all druid healing spells does cancel moonkin form.

Holy shock does NOT work inside moonkin form currently.
This is how it should be.
