### ISSUE TITLE
Metaform bugg

### ISSUE THREAD

**Issue by Sandor05** [Project-Deus/Deus-Classless-Issues#9]
if you use anyspell which are not warlock while in metaform you  can´t use the meta form spells anymore but you still get the 20% dmg buff etc/  spells i used where scorch and fireblast

**Comment by Blandmarrow** [comment]
Report is correct.

**Comment by UltraNix** [comment]
Clientside bug - can't be fixed in core.

**Comment by UltraNix** [comment]
Fixed.
