### ISSUE TITLE
Icy veins immunity to pushback not working

### ISSUE THREAD

**Issue by Above01** [Project-Deus/Deus-Classless-Issues#90]
**Describe the bug**
Icy veins '100% pushback reduced' is not reducing pushback from damaging abilities

**To Reproduce**
1. Cast icy veins 
2. Cast a spell
3. Get damaged
4. Pushback
5. 
**Expected behavior**
No pushback on spells during icy veins

**Comment by Blandmarrow** [comment]
Confirmed report.

CORRECTION:
This is currently intended behavior, however it should reduce pushback for all spells, which is a part of the class masking project which is not implemented yet.
