### ISSUE TITLE
Templar's Verdict not doing correct damage

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#91]
Templar's Verdict is hitting less for 100% weapon damage at max holy power stacks, when it should be doing 235% weapon damage untalented

**Comment by Blandmarrow** [comment]
CORRECTION:

Tooltip states 235% weapon damage but has been changed to 190% weapon damage in changelog.
Templar's Verdict seems to be doing correct damage.

Correct tooltip to 190% weapon damage at 3 stacks.

**Comment by WarlordXecc** [comment]
Fixed
