### ISSUE TITLE
Felheart 3p bonus not working

### ISSUE THREAD

**Issue by Luiswastaken** [Project-Deus/Deus-Classless-Issues#93]
**Describe the bug**
3 set felheart states "Health gained from Drain Life increased by 15%" but due to how drain life works in cata (healing 2% max health) this bonus seems broken.

**To Reproduce**
1. Equip 3 piece felheart
2. Watch as drainlife healing is unchanged

**Expected behavior**

I used 3p Arcanist and healed for 173 per tick
Then used 3p Felheart and healed for 172 per tick.
The 1 healing difference is due to change in max health.

I think it should give me 197 health per tick instead

**Comment by Blandmarrow** [comment]
Confirmed report.

3 set bonus doesn't increase % health gained from drain life.
15% of 2% is 0.3 so is should be 2.3% of max health with set bonus.
