### ISSUE TITLE
Bear Form Armor Contribution

### ISSUE THREAD

**Issue by Kev500** [Project-Deus/Deus-Classless-Issues#94]
**Describe the bug**
Bear Form armor contribution does not work correctly. Plate and Mail armor contribution in bear form is still currently working.

**To Reproduce**
1. Go to 'Get Plate Armor'
2. Click on 'Bear Form'
3. Scroll down to 'Defense in Stats'

**Expected behavior**
It shouldn't work in bear form.

**Screenshots**
![image](https://user-images.githubusercontent.com/96515212/147388115-21dd34c2-e108-465b-b8d0-0ba22a1831a6.png)

**Comment by Blandmarrow** [comment]
Confirmed report.
