### ISSUE TITLE
Skull Bash

### ISSUE THREAD

**Issue by Kev500** [Project-Deus/Deus-Classless-Issues#95]
**Describe the bug**
There is currently a talent "Brutal Impact" in the Feral Combat talent tree (ID: 16941) that reduces Skull Bashs cooldown by 50 seconds if talented twice. Skull Bashs cooldown is only 30 seconds base.

**To Reproduce**
1. Go to 'Talent 2 points into Brutal Impact'
2. Click on 'Skull Bash in either Cat or Bear form'
3. Enjoy the misery of any caster

**Expected behavior**
Skull Bash having a cooldown.

**Suggested Change**
Reduce the cooldown by 8 seconds per point making it a 14 second kick. Reason its not 10 is because Skull Bash is also a small dash making it better than kick if it was a 10 second cooldown.

**Comment by Blandmarrow** [comment]
Confirmed report.

Brutal impact currently can reduce CD of Skull Bash (both cat and bear) to 0 making it spamable.

Brutal Impact ID:
R1: 16940
R2: 16941

**Comment by WarlordXecc** [comment]
Skull Bash CD back to 60 second CD
