### ISSUE TITLE
Blackjack talent not applying debuff

### ISSUE THREAD

**Issue by Drakeare** [Project-Deus/Deus-Classless-Issues#96]
Breaking sap, reapplying sap, sap expiring does not apply the Blackjack talent to targets after recent patch. At one talent point no debuff or debuff animation is shown, at 2 talent points, no debuff but an debuff animation is shown on the target.

**Comment by Blandmarrow** [comment]
Confirmed report.

Blackjack talent does NOT apply debuff as it should on either rank.

ID: 
R1: 79123
R2: 79125
