### ISSUE TITLE
Slow Fall Glyph

### ISSUE THREAD

**Issue by Kev500** [Project-Deus/Deus-Classless-Issues#97]
**Describe the bug**
Slow Fall glyph not working at all, slow fall still costs Light Feathers after applying the glyph.

**To Reproduce**
1. Go to 'Mage Glyph Vendor'
2. Drag the glyph 'Glyph of Slow Fall' onto your glyph slot
3. Hover Slow Fall

**Expected behavior**
Slow Fall should be useable without carrying Light Feathers

**Screenshots**
![WoWScrnShot_122521_201659](https://user-images.githubusercontent.com/96515212/147392075-f596bbd8-c256-41b8-b73c-6d0ecd4aaffc.jpg)

**Comment by Blandmarrow** [comment]
Confirmed report.
